FROM redis:7.2.0-alpine
# For generate redis conf do command(in this folder)     wget -O redis.conf 'http://download.redis.io/redis-stable/redis.conf'
CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
